[package]
name = "bottles-winebridge"
version = "0.1.0"
edition = "2021"

[dependencies]
tonic = "0.12.3"
tokio = { version = "1.28.2", features = ["full"] }
prost = "0.13.4"
prost-types = "0.13.4"
serde = { version = "1.0.183", features = ["derive"] }

[dependencies.windows]
version = "0.58.0"
features = [
    "Data_Xml_Dom",
    "Win32_Foundation",
    "Win32_Security",
    "Win32_System_Threading",
    "Win32_UI_WindowsAndMessaging",
]

[build-dependencies]
tonic-build = "0.12.3"
